[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
auction = "DH5eappnLSkqwVRee1SKoiwRr3tk5GfjtqfdsKBzqP6j"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/nandom/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
